tunnel: bde0a2ad-19ce-4fee-8095-8c1a2ad7579d
credentials-file: /Users/itopa/.cloudflared/bde0a2ad-19ce-4fee-8095-8c1a2ad7579d.json

ingress:
  # MinIO S3 API endpoint
  - hostname: minio.confamd.com
    service: http://localhost:9000
  # MinIO Console (web interface)
  - hostname: minio-console.confamd.com
    service: http://localhost:9001
  # Platform application frontend - WebSocket requests to API Gateway
  - hostname: platform.confamd.com
    path: /socket.io/*
    service: http://localhost:5000
  # Platform application frontend - HTTP requests to API Gateway
  - hostname: platform.confamd.com
    service: http://localhost:5000
  - service: http_status:404
