tunnel: 00af0aa6-02a4-4c6d-8c8b-ad566348a8c0
credentials-file: /etc/cloudflared/00af0aa6-02a4-4c6d-8c8b-ad566348a8c0.json

ingress:
  - hostname: minio.confamd.com
    service: http://localhost:9000
  - hostname: minio-console.confamd.com
    service: http://localhost:9001
  # Platform application frontend - WebSocket requests to API Gateway
  - hostname: platform-admin.confamd.com
    path: /socket.io/*
    service: http://host.docker.internal:5000
  # Platform application frontend - HTTP requests to API Gateway
  - hostname: platform-admin.confamd.com
    service: http://host.docker.internal:5000
  - service: http_status:404
