version: '3.3'
services:
    nats:
        container_name: nats-server
        ports:
            
            - '4222:4222'
            
        volumes:
            - './nats-server.conf:/nats-server.conf'
        restart: unless-stopped
        image: nats