# Stage 1: Build the application
FROM node:18-alpine AS build

# Install OpenSSL
RUN apk add --no-cache openssl
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json pnpm-lock.yaml ./

ENV PUPPETEER_SKIP_DOWNLOAD=true

# Install dependencies with frozen lockfile
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy the rest of the application code
COPY . .

# Ensure we have the latest Prisma client types
RUN cd libs/prisma-service && npx prisma generate --schema=./prisma/schema.prisma

# Install any additional dependencies that might be needed
RUN pnpm install --ignore-scripts

# Build the user service
RUN pnpm run build user

# Stage 2: Create the final image
FROM node:18-alpine

RUN apk add --no-cache openssl
# Set the working directory
WORKDIR /app

# Copy the compiled code from the build stage
COPY --from=build /app/dist/apps/user/ ./dist/apps/user/

# Copy the libs folder from the build stage (includes generated Prisma client)
COPY --from=build /app/libs/ ./libs/

# Copy the node_modules (includes generated Prisma client)
COPY --from=build /app/node_modules  ./node_modules


# Set the command to run the microservice
CMD ["sh", "-c", "cd libs/prisma-service && npx prisma migrate deploy --schema=./prisma/schema.prisma && npx prisma generate --schema=./prisma/schema.prisma && cd ../.. && node dist/apps/user/main.js"]
